# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ec-bcwKUXFFxf0ADa2X_l0ds1DxrYSmK
"""

# ==============================
# 📊 CSV 파일용 자동 EDA 코드 (Colab 한글 완벽 호환)
# ==============================
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
import matplotlib as mpl
import glob

import seaborn as sns
import pandas as pd
import numpy as np


# ==============================
# 1️⃣ CSV 파일 불러오기
# ==============================
df = pd.read_csv("/content/drive/MyDrive/기계학습/팀플/Data/POS_all.csv", encoding='utf-8')

# ==============================
# 2️⃣ 데이터 전처리
# ==============================
# '영업일자'를 datetime으로 변환
df['영업일자'] = pd.to_datetime(df['영업일자'], errors='coerce')

# '일매출', '객단가'를 숫자로 변환 (쉼표, 공백 제거)
for col in ['일매출', '객단가']:
    df[col] = df[col].astype(str).str.replace(',', '').str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 결측 제거
df = df.dropna(subset=['영업일자'])

# 연도, 월, 일 추가
df['연도'] = df['영업일자'].dt.year
df['월'] = df['영업일자'].dt.month
df['일'] = df['영업일자'].dt.day

# ==============================
# 3️⃣ 연도별 집계 (x축: 월)
# ==============================
yearly_sales = df.groupby(['연도', '월'], as_index=False)[['일매출', '매출건수']].sum()

# ==============================
# 4️⃣ 월별 집계 (x축: 날짜)
# ==============================
# 최신 연도 기준으로 데이터 필터링
latest_year = df['연도'].max()

# ==============================
# 5️⃣ 시각화
# ==============================

plt.figure(figsize=(12, 6))
sns.lineplot(data=yearly_sales, x='월', y='일매출', hue='연도', marker='o')
plt.title('연도별 월평균 일매출 추이')
plt.xlabel('월')
plt.ylabel('일매출')
plt.legend(title='연도')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(data=yearly_sales, x='월', y='매출건수', hue='연도', marker='o')
plt.title('연도별 월별 매출건수 추이')
plt.xlabel('월')
plt.ylabel('매출건수')
plt.legend(title='연도')
plt.show()

# ==============================
# 3️⃣ 월별 합계 데이터 (연도별)
# ==============================
monthly_summary = (
    df.groupby(['연도', '월'], as_index=False)[['일매출', '매출건수']]
    .sum()
    .sort_values(['연도', '월'])
)

# ==============================
# 4️⃣ 그래프 시각화 (3행 2열: 연도별 묶음)
# ==============================

years = sorted(df['연도'].unique())
sns.set_style("whitegrid")

fig, axes = plt.subplots(len(years), 2, figsize=(14, 5 * len(years)))

for i, year in enumerate(years):
    sub = monthly_summary[monthly_summary['연도'] == year]

    # (왼쪽) 일매출
    sns.lineplot(data=sub, x='월', y='일매출', marker='o', ax=axes[i, 0], color='tab:blue')
    axes[i, 0].set_title(f"{year}년 월별 일매출 추이", fontsize=13)
    axes[i, 0].set_xlabel("월")
    axes[i, 0].set_ylabel("일매출")
    axes[i, 0].grid(True)

    # (오른쪽) 매출건수
    sns.lineplot(data=sub, x='월', y='매출건수', marker='o', ax=axes[i, 1], color='tab:orange')
    axes[i, 1].set_title(f"{year}년 월별 매출건수 추이", fontsize=13)
    axes[i, 1].set_xlabel("월")
    axes[i, 1].set_ylabel("매출건수")
    axes[i, 1].grid(True)

plt.tight_layout()
plt.show()

# ✅ 1. 나눔 폰트 설치
!apt-get update -qq
!apt-get install -qq fonts-nanum

# ✅ 2. Matplotlib에 폰트 수동 등록
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
import matplotlib as mpl
import glob

# Colab에 설치된 나눔폰트 경로 찾기
font_paths = glob.glob("/usr/share/fonts/truetype/nanum/*.ttf")
for path in font_paths:
    fm.fontManager.addfont(path)

# ✅ 3. 폰트 설정 적용
plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

# ✅ 4. 테스트
plt.title("🎉 한글 폰트 드디어 잘 나온다!")
plt.plot([1, 2, 3], [1, 4, 9])
plt.show()